name: wiwit_app
description: "Wiwit Finance Tracker mobile app"
publish_to: "none"
version: 0.1.0-alpha.3+3

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  animated_digit: ^3.3.3
  chopper: ^8.7.0
  cupertino_ui: any
  device_info_plus: ^13.2.0
  fl_chart: ^1.2.0
  flutter_riverpod: ^3.3.2
  flutter_secure_storage: ^10.3.1
  gap: ^3.0.1
  intl: ^0.20.3
  json_annotation: ^4.12.0
  material_ui: ^1.1.1
  package_info_plus: ^10.2.1
  riverpod_annotation: ^4.0.3
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.15.1
  chopper_generator: ^8.7.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.14.0
  riverpod_generator: ^4.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DM_Sans/DMSans-VariableFont_opsz,wght.ttf
        - asset: fonts/DM_Sans/DMSans-Italic-VariableFont_opsz,wght.ttf
          style: italic
  assets:
    - assets/logos/
